package httpapi

import (
	"bytes"
	"context"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/coderGtm/delta/go/config"
)

// TestRequestIDVisibleToRequestLog verifies the request id generated by the
// RequestID middleware reaches the request-completion log line produced by
// RequestLog. RequestID must wrap RequestLog so the log sees the id-injected
// request; composing it the other way round leaves requestId empty.
func TestRequestIDVisibleToRequestLog(t *testing.T) {
	var buf bytes.Buffer
	logger := slog.New(slog.NewTextHandler(&buf, nil))
	handler := NewRouter(logger, config.Config{TrustProxyHeaders: true}, func(ctx context.Context) error { return nil }, nil, func(h http.Handler) http.Handler { return h }, http.NewServeMux())

	rec := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/healthz", nil)
	handler.ServeHTTP(rec, req)

	headerID := rec.Header().Get("X-Request-Id")
	if headerID == "" {
		t.Fatalf("response missing X-Request-Id")
	}
	logged := buf.String()
	if !strings.Contains(logged, "requestId="+headerID) {
		t.Fatalf("log line missing request id %q:\n%s", headerID, logged)
	}
}
