// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const InsertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (actor_user_id, action, entity_type, entity_id, metadata_json, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_user_id, action, entity_type, entity_id, metadata_json, ip_address, user_agent, created_at, updated_at
`

type InsertAuditEventParams struct {
	ActorUserID  pgtype.UUID
	Action       string
	EntityType   string
	EntityID     pgtype.UUID
	MetadataJson []byte
	IpAddress    pgtype.Text
	UserAgent    pgtype.Text
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, InsertAuditEvent,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.MetadataJson,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.MetadataJson,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
