// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceEntry struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OutletID  pgtype.UUID
	Type      string
	EntryTime pgtype.Timestamptz
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AuditEvent struct {
	ID           pgtype.UUID
	ActorUserID  pgtype.UUID
	Action       string
	EntityType   string
	EntityID     pgtype.UUID
	MetadataJson []byte
	IpAddress    pgtype.Text
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Outlet struct {
	ID                            pgtype.UUID
	Name                          string
	Latitude                      pgtype.Numeric
	Longitude                     pgtype.Numeric
	RadiusMeters                  int32
	GeofenceEnabled               bool
	RemovedAt                     pgtype.Timestamptz
	RemovedByUserID               pgtype.UUID
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	ShowRecentEntriesToEmployees  bool
	ShowTotalTimeTodayToEmployees bool
}

type OutletMembership struct {
	ID              pgtype.UUID
	OutletID        pgtype.UUID
	UserID          pgtype.UUID
	Role            string
	Status          string
	DisplayName     string
	InvitedByUserID pgtype.UUID
	RemovedAt       pgtype.Timestamptz
	RemovedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	AuthUid         pgtype.Text
	Name            string
	Email           pgtype.Text
	Phone           pgtype.Text
	HistoricalEmail pgtype.Text
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
