// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outlets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountMembershipsForOutlet = `-- name: CountMembershipsForOutlet :one
SELECT count(*) FROM outlet_memberships WHERE outlet_id = $1 AND removed_at IS NULL
`

func (q *Queries) CountMembershipsForOutlet(ctx context.Context, outletID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMembershipsForOutlet, outletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMembershipsForUserByStatus = `-- name: CountMembershipsForUserByStatus :one
SELECT count(*) FROM outlet_memberships m
JOIN outlets o ON o.id = m.outlet_id
WHERE m.user_id = $1 AND m.status = $2 AND m.removed_at IS NULL AND o.removed_at IS NULL
`

type CountMembershipsForUserByStatusParams struct {
	UserID pgtype.UUID
	Status string
}

func (q *Queries) CountMembershipsForUserByStatus(ctx context.Context, arg CountMembershipsForUserByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountMembershipsForUserByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateMembership = `-- name: CreateMembership :one
INSERT INTO outlet_memberships
  (outlet_id, user_id, role, status, display_name, invited_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at
`

type CreateMembershipParams struct {
	OutletID        pgtype.UUID
	UserID          pgtype.UUID
	Role            string
	Status          string
	DisplayName     string
	InvitedByUserID pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, CreateMembership,
		arg.OutletID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.DisplayName,
		arg.InvitedByUserID,
	)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (name, latitude, longitude, radius_meters)
VALUES ($1, $2, $3, $4)
RETURNING id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at
`

type CreateOutletParams struct {
	Name         string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	RadiusMeters int32
}

func (q *Queries) CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, CreateOutlet,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteOutlet = `-- name: DeleteOutlet :one
UPDATE outlets SET removed_at = now(), removed_by_user_id = $2, updated_at = now()
WHERE id = $1 RETURNING id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at
`

type DeleteOutletParams struct {
	ID              pgtype.UUID
	RemovedByUserID pgtype.UUID
}

func (q *Queries) DeleteOutlet(ctx context.Context, arg DeleteOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, DeleteOutlet, arg.ID, arg.RemovedByUserID)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMembershipByIDIncludingRemoved = `-- name: GetMembershipByIDIncludingRemoved :one
SELECT id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at FROM outlet_memberships WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMembershipByIDIncludingRemoved(ctx context.Context, id pgtype.UUID) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, GetMembershipByIDIncludingRemoved, id)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMembershipByOutletAndUser = `-- name: GetMembershipByOutletAndUser :one
SELECT id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at FROM outlet_memberships
WHERE outlet_id = $1 AND user_id = $2 AND removed_at IS NULL LIMIT 1
`

type GetMembershipByOutletAndUserParams struct {
	OutletID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetMembershipByOutletAndUser(ctx context.Context, arg GetMembershipByOutletAndUserParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, GetMembershipByOutletAndUser, arg.OutletID, arg.UserID)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMembershipByOutletAndUserIncludingRemoved = `-- name: GetMembershipByOutletAndUserIncludingRemoved :one
SELECT id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at FROM outlet_memberships
WHERE outlet_id = $1 AND user_id = $2 LIMIT 1
`

type GetMembershipByOutletAndUserIncludingRemovedParams struct {
	OutletID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetMembershipByOutletAndUserIncludingRemoved(ctx context.Context, arg GetMembershipByOutletAndUserIncludingRemovedParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, GetMembershipByOutletAndUserIncludingRemoved, arg.OutletID, arg.UserID)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMembershipDetailsByID = `-- name: GetMembershipDetailsByID :one
SELECT m.id, m.outlet_id, m.user_id, m.role, m.status, m.display_name, m.invited_by_user_id, m.removed_at, m.removed_by_user_id, m.created_at, m.updated_at,
       u.id AS user_id, u.name AS user_name, u.email AS user_email,
       o.id AS outlet_id, o.name AS outlet_name, o.latitude, o.longitude, o.radius_meters,
       o.geofence_enabled, o.removed_at AS outlet_removed_at, o.created_at AS outlet_created_at,
       o.updated_at AS outlet_updated_at,
       iu.id AS invited_by_user_id, iu.name AS invited_by_user_name
FROM outlet_memberships m
JOIN users u ON u.id = m.user_id
JOIN outlets o ON o.id = m.outlet_id
LEFT JOIN users iu ON iu.id = m.invited_by_user_id
WHERE m.id = $1 AND m.removed_at IS NULL
LIMIT 1
`

type GetMembershipDetailsByIDRow struct {
	ID                pgtype.UUID
	OutletID          pgtype.UUID
	UserID            pgtype.UUID
	Role              string
	Status            string
	DisplayName       string
	InvitedByUserID   pgtype.UUID
	RemovedAt         pgtype.Timestamptz
	RemovedByUserID   pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	UserID_2          pgtype.UUID
	UserName          string
	UserEmail         pgtype.Text
	OutletID_2        pgtype.UUID
	OutletName        string
	Latitude          pgtype.Numeric
	Longitude         pgtype.Numeric
	RadiusMeters      int32
	GeofenceEnabled   bool
	OutletRemovedAt   pgtype.Timestamptz
	OutletCreatedAt   pgtype.Timestamptz
	OutletUpdatedAt   pgtype.Timestamptz
	InvitedByUserID_2 pgtype.UUID
	InvitedByUserName pgtype.Text
}

func (q *Queries) GetMembershipDetailsByID(ctx context.Context, id pgtype.UUID) (GetMembershipDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, GetMembershipDetailsByID, id)
	var i GetMembershipDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.OutletID_2,
		&i.OutletName,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.OutletRemovedAt,
		&i.OutletCreatedAt,
		&i.OutletUpdatedAt,
		&i.InvitedByUserID_2,
		&i.InvitedByUserName,
	)
	return i, err
}

const GetOutletByID = `-- name: GetOutletByID :one
SELECT id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at FROM outlets WHERE id = $1 AND removed_at IS NULL LIMIT 1
`

func (q *Queries) GetOutletByID(ctx context.Context, id pgtype.UUID) (Outlet, error) {
	row := q.db.QueryRow(ctx, GetOutletByID, id)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOutletByIDIncludingDeleted = `-- name: GetOutletByIDIncludingDeleted :one
SELECT id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at FROM outlets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOutletByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (Outlet, error) {
	row := q.db.QueryRow(ctx, GetOutletByIDIncludingDeleted, id)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListMembershipsForOutlet = `-- name: ListMembershipsForOutlet :many
SELECT m.id, m.outlet_id, m.user_id, m.role, m.status, m.display_name, m.invited_by_user_id, m.removed_at, m.removed_by_user_id, m.created_at, m.updated_at, u.id AS user_id, u.name AS user_name, u.email AS user_email,
       iu.id AS invited_by_user_id, iu.name AS invited_by_user_name
FROM outlet_memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN users iu ON iu.id = m.invited_by_user_id
WHERE m.outlet_id = $1 AND m.removed_at IS NULL
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMembershipsForOutletParams struct {
	OutletID pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListMembershipsForOutletRow struct {
	ID                pgtype.UUID
	OutletID          pgtype.UUID
	UserID            pgtype.UUID
	Role              string
	Status            string
	DisplayName       string
	InvitedByUserID   pgtype.UUID
	RemovedAt         pgtype.Timestamptz
	RemovedByUserID   pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	UserID_2          pgtype.UUID
	UserName          string
	UserEmail         pgtype.Text
	InvitedByUserID_2 pgtype.UUID
	InvitedByUserName pgtype.Text
}

func (q *Queries) ListMembershipsForOutlet(ctx context.Context, arg ListMembershipsForOutletParams) ([]ListMembershipsForOutletRow, error) {
	rows, err := q.db.Query(ctx, ListMembershipsForOutlet, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForOutletRow{}
	for rows.Next() {
		var i ListMembershipsForOutletRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.DisplayName,
			&i.InvitedByUserID,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
			&i.InvitedByUserID_2,
			&i.InvitedByUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMembershipsForOutletByUser = `-- name: ListMembershipsForOutletByUser :many
SELECT id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at FROM outlet_memberships
WHERE outlet_id = $1 AND user_id = $2
ORDER BY created_at ASC
`

type ListMembershipsForOutletByUserParams struct {
	OutletID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) ListMembershipsForOutletByUser(ctx context.Context, arg ListMembershipsForOutletByUserParams) ([]OutletMembership, error) {
	rows, err := q.db.Query(ctx, ListMembershipsForOutletByUser, arg.OutletID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutletMembership{}
	for rows.Next() {
		var i OutletMembership
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.DisplayName,
			&i.InvitedByUserID,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMembershipsForUserByStatus = `-- name: ListMembershipsForUserByStatus :many
SELECT m.id, m.outlet_id, m.user_id, m.role, m.status, m.display_name, m.invited_by_user_id, m.removed_at, m.removed_by_user_id, m.created_at, m.updated_at, o.id AS outlet_id, o.name AS outlet_name, o.latitude, o.longitude, o.radius_meters,
       o.geofence_enabled, o.removed_at AS outlet_removed_at, o.created_at AS outlet_created_at,
       o.updated_at AS outlet_updated_at
FROM outlet_memberships m
JOIN outlets o ON o.id = m.outlet_id
WHERE m.user_id = $1 AND m.status = $2 AND m.removed_at IS NULL AND o.removed_at IS NULL
ORDER BY m.updated_at DESC
LIMIT $3 OFFSET $4
`

type ListMembershipsForUserByStatusParams struct {
	UserID pgtype.UUID
	Status string
	Limit  int32
	Offset int32
}

type ListMembershipsForUserByStatusRow struct {
	ID              pgtype.UUID
	OutletID        pgtype.UUID
	UserID          pgtype.UUID
	Role            string
	Status          string
	DisplayName     string
	InvitedByUserID pgtype.UUID
	RemovedAt       pgtype.Timestamptz
	RemovedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	OutletID_2      pgtype.UUID
	OutletName      string
	Latitude        pgtype.Numeric
	Longitude       pgtype.Numeric
	RadiusMeters    int32
	GeofenceEnabled bool
	OutletRemovedAt pgtype.Timestamptz
	OutletCreatedAt pgtype.Timestamptz
	OutletUpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListMembershipsForUserByStatus(ctx context.Context, arg ListMembershipsForUserByStatusParams) ([]ListMembershipsForUserByStatusRow, error) {
	rows, err := q.db.Query(ctx, ListMembershipsForUserByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserByStatusRow{}
	for rows.Next() {
		var i ListMembershipsForUserByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.DisplayName,
			&i.InvitedByUserID,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OutletID_2,
			&i.OutletName,
			&i.Latitude,
			&i.Longitude,
			&i.RadiusMeters,
			&i.GeofenceEnabled,
			&i.OutletRemovedAt,
			&i.OutletCreatedAt,
			&i.OutletUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveMembership = `-- name: RemoveMembership :one
UPDATE outlet_memberships
SET removed_at = now(), removed_by_user_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at
`

type RemoveMembershipParams struct {
	ID              pgtype.UUID
	RemovedByUserID pgtype.UUID
}

func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, RemoveMembership, arg.ID, arg.RemovedByUserID)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateMembershipDisplayName = `-- name: UpdateMembershipDisplayName :one
UPDATE outlet_memberships SET display_name = $2, updated_at = now() WHERE id = $1 RETURNING id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at
`

type UpdateMembershipDisplayNameParams struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) UpdateMembershipDisplayName(ctx context.Context, arg UpdateMembershipDisplayNameParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, UpdateMembershipDisplayName, arg.ID, arg.DisplayName)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateMembershipInvite = `-- name: UpdateMembershipInvite :one
UPDATE outlet_memberships
SET role = $2, status = $3, invited_by_user_id = $4, removed_at = NULL, removed_by_user_id = NULL, updated_at = now()
WHERE id = $1
RETURNING id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at
`

type UpdateMembershipInviteParams struct {
	ID              pgtype.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
}

func (q *Queries) UpdateMembershipInvite(ctx context.Context, arg UpdateMembershipInviteParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, UpdateMembershipInvite,
		arg.ID,
		arg.Role,
		arg.Status,
		arg.InvitedByUserID,
	)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE outlet_memberships SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, outlet_id, user_id, role, status, display_name, invited_by_user_id, removed_at, removed_by_user_id, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (OutletMembership, error) {
	row := q.db.QueryRow(ctx, UpdateMembershipStatus, arg.ID, arg.Status)
	var i OutletMembership
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.InvitedByUserID,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateOutlet = `-- name: UpdateOutlet :one
UPDATE outlets
SET name = $2, latitude = $3, longitude = $4, radius_meters = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at
`

type UpdateOutletParams struct {
	ID           pgtype.UUID
	Name         string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	RadiusMeters int32
}

func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, UpdateOutlet,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateOutletGeofence = `-- name: UpdateOutletGeofence :one
UPDATE outlets SET geofence_enabled = $2, updated_at = now() WHERE id = $1 RETURNING id, name, latitude, longitude, radius_meters, geofence_enabled, removed_at, removed_by_user_id, created_at, updated_at
`

type UpdateOutletGeofenceParams struct {
	ID              pgtype.UUID
	GeofenceEnabled bool
}

func (q *Queries) UpdateOutletGeofence(ctx context.Context, arg UpdateOutletGeofenceParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, UpdateOutletGeofence, arg.ID, arg.GeofenceEnabled)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.GeofenceEnabled,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
