// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, expires_at, revoked, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, expires_at, revoked, user_id, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	UserID    pgtype.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, CreateRefreshToken,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Revoked,
		arg.UserID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteOldRevokedRefreshTokens = `-- name: DeleteOldRevokedRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE revoked = true AND updated_at < $1
`

func (q *Queries) DeleteOldRevokedRefreshTokens(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteOldRevokedRefreshTokens, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, expires_at, revoked, user_id, created_at, updated_at FROM refresh_tokens WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, GetRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :execrows
UPDATE refresh_tokens SET revoked = true, updated_at = now()
WHERE user_id = $1 AND revoked = false
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, RevokeAllRefreshTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateRefreshTokenRevoked = `-- name: UpdateRefreshTokenRevoked :one
UPDATE refresh_tokens SET revoked = $2, updated_at = now() WHERE id = $1 RETURNING id, token_hash, expires_at, revoked, user_id, created_at, updated_at
`

type UpdateRefreshTokenRevokedParams struct {
	ID      pgtype.UUID
	Revoked bool
}

func (q *Queries) UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, UpdateRefreshTokenRevoked, arg.ID, arg.Revoked)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
