// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAttendanceByOutlet = `-- name: CountAttendanceByOutlet :one
SELECT count(*) FROM attendance_entries WHERE outlet_id = $1
`

func (q *Queries) CountAttendanceByOutlet(ctx context.Context, outletID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountAttendanceByOutlet, outletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAttendanceByOutletAndUser = `-- name: CountAttendanceByOutletAndUser :one
SELECT count(*) FROM attendance_entries WHERE outlet_id = $1 AND user_id = $2
`

type CountAttendanceByOutletAndUserParams struct {
	OutletID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) CountAttendanceByOutletAndUser(ctx context.Context, arg CountAttendanceByOutletAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAttendanceByOutletAndUser, arg.OutletID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAttendanceEntry = `-- name: CreateAttendanceEntry :one
INSERT INTO attendance_entries (user_id, outlet_id, type, entry_time, latitude, longitude, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at
`

type CreateAttendanceEntryParams struct {
	UserID    pgtype.UUID
	OutletID  pgtype.UUID
	Type      string
	EntryTime pgtype.Timestamptz
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateAttendanceEntry(ctx context.Context, arg CreateAttendanceEntryParams) (AttendanceEntry, error) {
	row := q.db.QueryRow(ctx, CreateAttendanceEntry,
		arg.UserID,
		arg.OutletID,
		arg.Type,
		arg.EntryTime,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedBy,
	)
	var i AttendanceEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.Type,
		&i.EntryTime,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAttendanceEntry = `-- name: DeleteAttendanceEntry :exec
DELETE FROM attendance_entries WHERE id = $1
`

func (q *Queries) DeleteAttendanceEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAttendanceEntry, id)
	return err
}

const GetAttendanceEntryByIDAndOutlet = `-- name: GetAttendanceEntryByIDAndOutlet :one
SELECT id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at FROM attendance_entries WHERE id = $1 AND outlet_id = $2 LIMIT 1
`

type GetAttendanceEntryByIDAndOutletParams struct {
	ID       pgtype.UUID
	OutletID pgtype.UUID
}

func (q *Queries) GetAttendanceEntryByIDAndOutlet(ctx context.Context, arg GetAttendanceEntryByIDAndOutletParams) (AttendanceEntry, error) {
	row := q.db.QueryRow(ctx, GetAttendanceEntryByIDAndOutlet, arg.ID, arg.OutletID)
	var i AttendanceEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.Type,
		&i.EntryTime,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAttendanceByOutlet = `-- name: ListAttendanceByOutlet :many
SELECT id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at FROM attendance_entries
WHERE outlet_id = $1
ORDER BY entry_time DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListAttendanceByOutletParams struct {
	OutletID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListAttendanceByOutlet(ctx context.Context, arg ListAttendanceByOutletParams) ([]AttendanceEntry, error) {
	rows, err := q.db.Query(ctx, ListAttendanceByOutlet, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceEntry{}
	for rows.Next() {
		var i AttendanceEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OutletID,
			&i.Type,
			&i.EntryTime,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAttendanceByOutletAndUser = `-- name: ListAttendanceByOutletAndUser :many
SELECT id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at FROM attendance_entries
WHERE outlet_id = $1 AND user_id = $2
ORDER BY entry_time DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListAttendanceByOutletAndUserParams struct {
	OutletID pgtype.UUID
	UserID   pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListAttendanceByOutletAndUser(ctx context.Context, arg ListAttendanceByOutletAndUserParams) ([]AttendanceEntry, error) {
	rows, err := q.db.Query(ctx, ListAttendanceByOutletAndUser,
		arg.OutletID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceEntry{}
	for rows.Next() {
		var i AttendanceEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OutletID,
			&i.Type,
			&i.EntryTime,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAttendanceByOutletUserRange = `-- name: ListAttendanceByOutletUserRange :many
SELECT id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at FROM attendance_entries
WHERE outlet_id = $1 AND user_id = $2 AND entry_time >= $3 AND entry_time < $4
ORDER BY entry_time ASC
`

type ListAttendanceByOutletUserRangeParams struct {
	OutletID    pgtype.UUID
	UserID      pgtype.UUID
	EntryTime   pgtype.Timestamptz
	EntryTime_2 pgtype.Timestamptz
}

func (q *Queries) ListAttendanceByOutletUserRange(ctx context.Context, arg ListAttendanceByOutletUserRangeParams) ([]AttendanceEntry, error) {
	rows, err := q.db.Query(ctx, ListAttendanceByOutletUserRange,
		arg.OutletID,
		arg.UserID,
		arg.EntryTime,
		arg.EntryTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceEntry{}
	for rows.Next() {
		var i AttendanceEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OutletID,
			&i.Type,
			&i.EntryTime,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAttendanceEntry = `-- name: UpdateAttendanceEntry :one
UPDATE attendance_entries
SET type = $2, entry_time = $3, latitude = $4, longitude = $5, updated_by = $6, updated_at = now()
WHERE id = $1
RETURNING id, user_id, outlet_id, type, entry_time, latitude, longitude, created_by, updated_by, created_at, updated_at
`

type UpdateAttendanceEntryParams struct {
	ID        pgtype.UUID
	Type      string
	EntryTime pgtype.Timestamptz
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateAttendanceEntry(ctx context.Context, arg UpdateAttendanceEntryParams) (AttendanceEntry, error) {
	row := q.db.QueryRow(ctx, UpdateAttendanceEntry,
		arg.ID,
		arg.Type,
		arg.EntryTime,
		arg.Latitude,
		arg.Longitude,
		arg.UpdatedBy,
	)
	var i AttendanceEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.Type,
		&i.EntryTime,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
