// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAttendanceByOutlet(ctx context.Context, outletID pgtype.UUID) (int64, error)
	CountAttendanceByOutletAndUser(ctx context.Context, arg CountAttendanceByOutletAndUserParams) (int64, error)
	CountMembershipsForOutlet(ctx context.Context, outletID pgtype.UUID) (int64, error)
	CountMembershipsForUserByStatus(ctx context.Context, arg CountMembershipsForUserByStatusParams) (int64, error)
	CreateAttendanceEntry(ctx context.Context, arg CreateAttendanceEntryParams) (AttendanceEntry, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OutletMembership, error)
	CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAttendanceEntry(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteOldRevokedRefreshTokens(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error)
	DeleteOutlet(ctx context.Context, arg DeleteOutletParams) (Outlet, error)
	DeleteUserRow(ctx context.Context, id pgtype.UUID) (User, error)
	GetAttendanceEntryByIDAndOutlet(ctx context.Context, arg GetAttendanceEntryByIDAndOutletParams) (AttendanceEntry, error)
	GetMembershipByIDIncludingRemoved(ctx context.Context, id pgtype.UUID) (OutletMembership, error)
	GetMembershipByOutletAndUser(ctx context.Context, arg GetMembershipByOutletAndUserParams) (OutletMembership, error)
	GetMembershipByOutletAndUserIncludingRemoved(ctx context.Context, arg GetMembershipByOutletAndUserIncludingRemovedParams) (OutletMembership, error)
	GetMembershipDetailsByID(ctx context.Context, id pgtype.UUID) (GetMembershipDetailsByIDRow, error)
	GetOutletByID(ctx context.Context, id pgtype.UUID) (Outlet, error)
	GetOutletByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (Outlet, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByAuthUID(ctx context.Context, authUid pgtype.Text) (User, error)
	GetUserByEmailCaseInsensitive(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	ListAttendanceByOutlet(ctx context.Context, arg ListAttendanceByOutletParams) ([]AttendanceEntry, error)
	ListAttendanceByOutletAndUser(ctx context.Context, arg ListAttendanceByOutletAndUserParams) ([]AttendanceEntry, error)
	ListAttendanceByOutletUserRange(ctx context.Context, arg ListAttendanceByOutletUserRangeParams) ([]AttendanceEntry, error)
	ListMembershipsForOutlet(ctx context.Context, arg ListMembershipsForOutletParams) ([]ListMembershipsForOutletRow, error)
	ListMembershipsForOutletByUser(ctx context.Context, arg ListMembershipsForOutletByUserParams) ([]OutletMembership, error)
	ListMembershipsForUserByStatus(ctx context.Context, arg ListMembershipsForUserByStatusParams) ([]ListMembershipsForUserByStatusRow, error)
	RemoveMembership(ctx context.Context, arg RemoveMembershipParams) (OutletMembership, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	UpdateAttendanceEntry(ctx context.Context, arg UpdateAttendanceEntryParams) (AttendanceEntry, error)
	UpdateMembershipDisplayName(ctx context.Context, arg UpdateMembershipDisplayNameParams) (OutletMembership, error)
	UpdateMembershipInvite(ctx context.Context, arg UpdateMembershipInviteParams) (OutletMembership, error)
	UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (OutletMembership, error)
	UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error)
	UpdateOutletGeofence(ctx context.Context, arg UpdateOutletGeofenceParams) (Outlet, error)
	UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
