// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (auth_uid, name, email, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	AuthUid pgtype.Text
	Name    string
	Email   pgtype.Text
	Phone   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.AuthUid,
		arg.Name,
		arg.Email,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteUserRow = `-- name: DeleteUserRow :one
UPDATE users
SET historical_email = email, email = NULL, deleted_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at
`

func (q *Queries) DeleteUserRow(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, DeleteUserRow, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByAuthUID = `-- name: GetUserByAuthUID :one
SELECT id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at FROM users WHERE auth_uid = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByAuthUID(ctx context.Context, authUid pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByAuthUID, authUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByEmailCaseInsensitive = `-- name: GetUserByEmailCaseInsensitive :one
SELECT id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmailCaseInsensitive(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmailCaseInsensitive, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at FROM users WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByIDIncludingDeleted = `-- name: GetUserByIDIncludingDeleted :one
SELECT id, auth_uid, name, email, phone, historical_email, deleted_at, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByIDIncludingDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.HistoricalEmail,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
